/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author xa.liberona
 */
public class VentanaSuperInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaSuperInicio
     */
    public VentanaSuperInicio() {
        initComponents();
        this.setTitle("Inicio");
        Image img = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/imagenPerfilLogin.png"));
        this.setIconImage(img);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnIniciar = new javax.swing.JButton();
        BtnCrear = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnIniciar.setText("Iniciar Sesion");
        BtnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarActionPerformed(evt);
            }
        });

        BtnCrear.setText("Crear Cuenta");
        BtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearActionPerformed(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(BtnIniciar)
                .addGap(46, 46, 46)
                .addComponent(BtnCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(BtnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        dispose();
        JOptionPane.showMessageDialog(this, "Gracias por utilizar nuestro programa.");
        dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarActionPerformed
        VentanaInicioSesion ventInicioSesion = new VentanaInicioSesion();
        ventInicioSesion.setLocationRelativeTo(null);
        ventInicioSesion.setDefaultCloseOperation(EXIT_ON_CLOSE);
        ventInicioSesion.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ventInicioSesion.setResizable(false);
        ventInicioSesion.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnIniciarActionPerformed

    private void BtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearActionPerformed
        VentanaRegistrarse ventRegistro = new VentanaRegistrarse();
        ventRegistro.setLocationRelativeTo(null);
        ventRegistro.setResizable(false);
        ventRegistro.setDefaultCloseOperation(EXIT_ON_CLOSE);
        ventRegistro.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ventRegistro.setVisible(true);
        JOptionPane.showMessageDialog(this, "Cargando ventana");
        dispose();
    }//GEN-LAST:event_BtnCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrear;
    private javax.swing.JButton BtnIniciar;
    private javax.swing.JButton BtnSalir;
    // End of variables declaration//GEN-END:variables
}
